// <auto-generated />
using System;
using DelhiHighCourt;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DelhiHighCourt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240912194043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DelhiHighCourt.caseDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bench")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlaCitation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaseNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaseReferred")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Citation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Coram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CoramCount")
                        .HasColumnType("integer");

                    b.Property<string>("Counsel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Court")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Dated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headnotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Overrule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OveruleBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PdfLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Petitioner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Reportable")
                        .HasColumnType("boolean");

                    b.Property<string>("Respondent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ssd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("caseDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
